### ISSUE TITLE
theme: monobloc

### ISSUE THREAD

**Issue by matrixise** [xaprb/xaprb-src#1]
Hi, thank you for your code, it's awesome.

just one question, you use the monobloc theme, where can I find it?

thank you,

**Comment by xaprb** [comment]
I'm sorry I missed this because of email filters. It's part of the Story Hugo theme, https://story.xaprb.com and github.com/xaprb/story. It isn't documented because I built a successor theme called Adirondack that I think is cleaner and more well built. The Story demo site has a slideshow explaining more details.
